name: Push en branch feature y automerge en develop
on:
  push:
    branches:
      - 'feature-**'
jobs:
  job1:
    name: Identificar en commit palabra clave = (Verde)
    if: ${{ contains(github.event.head_commit.message, '(Verde)') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Hacer merge de rama develop a feature 
      uses: tukasz/direct-merge-action@master
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}
    - name: Ejecución de pruebas unitarias
      id: correr-pruebas
      run: python -m unittest discover -s tests
    - name: Validar resultado sin errores y hacer merge de rama feature a develop
      if: ${{ success() }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUBACTIONSSECRET }}
        source-branch: ${{ github.ref }}
        target-branch: develop
        commit-message: "Automerge to develop "